modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Respawn%20Delay"
logoFile="icon.png"

[[mods]]
modId="respawndelay"
version="5.0"
displayName="Respawn Delay"
displayURL="https://serilum.com/mod/respawn-delay"
authors="Rick South"
description='''Players enter spectator mode on death for a configurable amount of time.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, aternosorg, Cherriesaurus, Linda Jansen, Michelle Smith, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.respawndelay]]
    modId="collective"
    type="required"
    versionRange="[8.25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.respawndelay]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "respawndelay.mixins.json"